
# Development mode jekyll configuration

# This will be picked up and the docs should display with a simple:
#
#     jekyll serve --watch

# See in _build/ for more advanced dev and prod considerations.

# links should either be relative or use {{site.path.website}}

url_root: http://0.0.0.0:4000

path:
  style: /style
  website: /website 
  v: /v

# site.url is deprecated in favour of site.path.website
# url: http://0.0.0.0:4000/website

# no longer putting things under /website; there is a new website/ dir in the folder structure for most things
baseurl: ""


# Use local copies of depenedencies (but provide the full URL so it is easy to switch to remote locations)

dependency_mode: local
dependency_urls:
  bootstrap.css: https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css
  bootstrap.js: https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js
  jquery.js: https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js


# These files should not be marked down (in addition to _* contents)

exclude: ['README.md']
