
# Development mode jekyll configuration

# This will be picked up and the docs should display with a simple:
#
#     jekyll serve --watch

# See in _scripts/ for more advanced dev and prod considerations.

# Deliberately add the "/website" to the URL to catch out places where a document uses a link starting "/" - these
# links should either be relative or use {{site.path.website}}. We want to preserve this behaviour to allow the possibility of
# "staging servers" which may publish preview copies of the site at a non-root URL.

url_root: http://0.0.0.0:4000

path:
  website: /website 

# site.url is deprecated in favour of site.path.website
url: http://0.0.0.0:4000/website

# this is the instruction to jekyll to put things under /website dir
baseurl: /website


# Use local copies of depenedencies (but provide the full URL so it is easy to switch to remote locations)

dependency_mode: local
dependency_urls:
  bootstrap.css: https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css
  bootstrap.js: https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js
  jquery.js: https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js


# These files should not be marked down (in addition to _* contents)

exclude: ['README.md']
